### ISSUE TITLE
Калькулятор не работает

### ISSUE THREAD

**Issue by alexdtat** [Belgrak/simple_calc_fortran#1]
Добрый вечер!

Я недавно заинтересовался Fortran. Слышал в Университете, он позволяет на суперкомпьютерах очень быстро и эффективно решать [математические](https://www.top500.org/lists/green500/) [задачки](https://graph500.org/) с использованием распараллеливания. Поскольку меня заинтересовали уже существующие вычислительные решения, я зашёл на GitHub и стал искать соответствующие репозитории, обнаружив там Ваш. Всё выглядит отлично, однако оказалось, что приведённое решение не работает на прикреплённых примерах (см. рис.). Просьба исправить. В остальном всё замечательно, спасибо! Ещё было бы неплохо русский язык добавить, конечно.

![image](https://user-images.githubusercontent.com/57017816/218335445-33ffb028-9390-4e7b-847b-ea4032467521.png)

**Comment by Belgrak** [comment]
Спасибо большое за проявленный интерес к моей работе, а также представленные недостатки. К сожалению, русификация отсутствует ввиду использования данной программы на суперкомпьютере [FRONTIER - HPE CRAY EX235A](https://www.top500.org/system/180047/)

**Comment by yanbosmu** [comment]
hello bro.
Do you have a GPU driver for ex235a in linux?
I am in desperate need of this!
thank you !!!

> Спасибо большое за проявленный интерес к моей работе, а также представленные недостатки. К сожалению, русификация отсутствует ввиду использования данной программы на суперкомпьютере [FRONTIER - HPE CRAY EX235A](https://www.top500.org/system/180047/)
