### ISSUE TITLE
Some problems with cross-platform

### ISSUE THREAD

**Issue by oveeernight** [Belgrak/simple_calc_fortran#2]
Hello from sunny Сyprus. I woke up. I ordered a 40 cm Florentine pizza for $80 with a portion of my favorite peppers and delicious garlic sauce, Jack Daniels and pineapples. Already looking forward to this food of the gods, salivating and flowing. In the meantime, I was browsing github and stumbled upon your project and with great regret found that it does not work on my machine. My setup
- Raspberry Pi
- Arch Linux

Could you please make the app cross platform so i can fully implement the solutions for my nature science homework?

**Comment by Belgrak** [comment]
Thank You for leaving this comment. I really appreciate Your interest in my project. However, I agree that running was tested just on few platforms (e.g. Risc-V).
