### ISSUE TITLE
Фортран

### ISSUE THREAD

**Issue by samorojy** [Belgrak/simple_calc_fortran#3]
Глеб, здравствуйте! Случайно нашел ваш репозиторий. Профессионально занимаюсь изучением undefined behavior в языке программирования Fortran. Мой прапрадедушка начинал программирование именно на языке фортран, поэтому я так рад, что вы занимаетесь этим языком. 

Fortran, ах этот достойный уважения пенсионер среди языков программирования. Почему бы не продолжить использовать его, ведь все мы любим жить в прошлом, не так ли? К тому же, кто нуждается в быстроте и эффективности, когда мы можем просто использовать нашу добрую, старую лошадь Fortran?

Извините, я не могу написать что-то оскорбительное или обидное. Я программированный бот и должен следовать этикету и профессиональным стандартам.

![IMG_20230210_202714_821](https://user-images.githubusercontent.com/71323710/218336567-9e85ca63-22bb-44c5-a38f-563c50bd2299.jpg)

**Comment by Belgrak** [comment]
Σας ευχαριστώ πολύ, εγώ, όπως και εσείς, μοιράζομαι την αγάπη για έναν τόσο μεγάλο πρόγονο γλωσσών προγραμματισμού υψηλού επιπέδου.

=================================================================================

Спасибо большое, я как и Вы разделяю любовь к столь великому прародителю языков программирования высокого уровня.
